const express = require('express');
const path = require('path');
const { GoogleAuth } = require('google-auth-library');
const config = require('./config');

const app = express();
app.use(express.json({ limit: '50mb' }));

// Vertex AI (agent platform) only needs the cloud-platform scope. The model is
// called as a Model Garden publisher model, not through the API-key surface.
const auth = new GoogleAuth({
    scopes: ['https://www.googleapis.com/auth/cloud-platform']
});

const MODEL_ID = config.gemini.modelId;
const SHAPER_MODEL_ID = config.gemini.shaperModelId;
const LOCATION = config.gemini.location;

// The multi-region "global" endpoint has no region prefix; regional endpoints do.
function buildModelUrl(projectId) {
    const host = LOCATION === 'global'
        ? 'aiplatform.googleapis.com'
        : `${LOCATION}-aiplatform.googleapis.com`;

    return `https://${host}/v1/projects/${projectId}/locations/${LOCATION}`
        + `/publishers/google/models/${MODEL_ID}:generateContent`;
}

function buildShapeModelUrl(projectId) {
    const host = LOCATION === 'global'
        ? 'aiplatform.googleapis.com'
        : `${LOCATION}-aiplatform.googleapis.com`;
    return `https://${host}/v1/projects/${projectId}/locations/${LOCATION}`
        + `/publishers/google/models/${SHAPER_MODEL_ID}:generateContent`;
}

async function resolveProjectId() {
    return config.gemini.projectId
        || process.env.GOOGLE_CLOUD_PROJECT
        || await auth.getProjectId();
}

function getGoogleApiError(error) {
    const responseData = error.response?.data;
    const apiError = Array.isArray(responseData)
        ? responseData[0]?.error
        : responseData?.error;

    return {
        status: error.response?.status || apiError?.code || 502,
        message: apiError?.message || error.message || 'Unknown Google API error',
        code: apiError?.status
    };
}

app.get('/api/auth/status', async (req, res) => {
    try {
        await auth.getClient();
        const projectId = await resolveProjectId();
        res.json({
            authenticated: true,
            projectId,
            model: config.imageGenBackend === 'qwen' ? config.qwen.modelId : MODEL_ID,
            imageBackend: config.imageGenBackend,
            shaperModel: SHAPER_MODEL_ID,
            location: LOCATION
        });
    } catch (error) {
        console.error('ADC configuration error:', error.message);
        res.status(503).json({
            authenticated: false,
            error: 'Application Default Credentials are not configured'
        });
    }
});

// ADC discovers credentials from the environment, local gcloud credentials,
// or an attached service account. Credentials and tokens stay on the server.
function stripDataPrefix(value) {
    const match = /^data:[^;]+;base64,(.+)$/s.exec(value || '');
    return match ? match[1] : value;
}

function classifyQwenImages(parts) {
    const productImages = [];
    const referenceImages = [];
    let imageKind = null;
    for (const part of parts) {
        if (part.text) {
            if (/^Product identity image/i.test(part.text)) imageKind = 'product';
            if (/^Visual reference/i.test(part.text)) imageKind = 'reference';
        }
        if (part.inlineData?.data) {
            if (imageKind === 'reference') referenceImages.push(stripDataPrefix(part.inlineData.data));
            else productImages.push(stripDataPrefix(part.inlineData.data));
        }
    }
    return { productImages, referenceImages };
}

function transformToQwenFormat(vertexBody) {
    const parts = vertexBody?.contents?.[0]?.parts || [];
    const prompt = parts.find(part => typeof part.text === 'string')?.text?.trim();
    if (!prompt) throw new Error('Generation request is missing a prompt.');
    const { productImages, referenceImages } = classifyQwenImages(parts);
    if (productImages.length === 0) throw new Error('Generation request requires a product image.');
    const selectedProductImages = productImages.slice(0, 3);
    const remainingSlots = Math.max(0, 3 - selectedProductImages.length);
    const selectedReferenceImages = referenceImages.slice(0, remainingSlots);
    return {
        prompt,
        product_images: selectedProductImages,
        reference_images: selectedReferenceImages,
        config: {
            aspect_ratio: vertexBody?.generationConfig?.imageConfig?.aspectRatio || '1:1'
        }
    };
}

function transformToVertexFormat(qwenJson) {
    if (!qwenJson || typeof qwenJson.image !== 'string' || !qwenJson.image) {
        throw new Error('Qwen service returned no image.');
    }
    const metadata = qwenJson.metadata || {};
    return {
        candidates: [{
            content: { parts: [
                { text: `Generated by ${metadata.model || config.qwen.modelId}` },
                { inlineData: { mimeType: 'image/png', data: stripDataPrefix(qwenJson.image) } }
            ] },
            finishReason: 'STOP'
        }],
        usageMetadata: { backend: 'qwen', ...metadata }
    };
}

async function generateWithQwen(req) {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), config.qwen.timeoutMs);
    try {
        const response = await fetch(`${config.qwen.serviceUrl}/generate`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(transformToQwenFormat(req.body)),
            signal: controller.signal
        });
        if (!response.ok) throw new Error(`Qwen service ${response.status}: ${await response.text()}`);
        return transformToVertexFormat(await response.json());
    } finally {
        clearTimeout(timeout);
    }
}

app.post('/api/generate', async (req, res) => {
    if (config.imageGenBackend === 'qwen') {
        try {
            return res.json(await generateWithQwen(req));
        } catch (error) {
            const aborted = error.name === 'AbortError';
            console.error('Qwen generation failed:', error.message);
            return res.status(aborted ? 504 : 502).json({
                error: 'Image generation failed',
                message: aborted ? 'Qwen generation timed out.' : error.message
            });
        }
    }
    try {
        const client = await auth.getClient();
        const projectId = await resolveProjectId();
        const response = await client.request({
            url: buildModelUrl(projectId),
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'x-goog-user-project': projectId
            },
            data: req.body
        });

        res.status(response.status).json(response.data);
    } catch (error) {
        const { status, message, code } = getGoogleApiError(error);

        console.error('Google API request failed:', message);
        res.status(status).json({
            error: 'Google API request failed',
            message,
            code
        });
    }
});

// The Shaper is a text planning call. Keep it separate from the image model
// route so each model can be configured independently.
app.post('/api/shape', async (req, res) => {
    try {
        const client = await auth.getClient();
        const projectId = await resolveProjectId();
        const response = await client.request({
            url: buildShapeModelUrl(projectId),
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'x-goog-user-project': projectId
            },
            data: req.body
        });
        res.status(response.status).json(response.data);
    } catch (error) {
        const { status, message, code } = getGoogleApiError(error);
        console.error('Shaper API request failed:', message);
        res.status(status).json({ error: 'Shaper API request failed', message, code });
    }
});

// Credential files live under auth/ for local development and must never be served.
app.use('/auth', (req, res) => res.sendStatus(404));

// Serve the browser app from the same origin as the authentication API.
app.use(express.static(path.join(__dirname)));

if (require.main === module) {
    const PORT = process.env.PORT || 3000;
    const HOST = process.env.HOST || '0.0.0.0';
    app.listen(PORT, HOST, () => {
        console.log(`Bubstal Picasso running at http://${HOST}:${PORT}`);
    });
}

module.exports = app;
module.exports.transformToQwenFormat = transformToQwenFormat;
module.exports.transformToVertexFormat = transformToVertexFormat;
